# Site settings
title: JKEEL
email: contact@JKEEL.io
description: Tune your sensation
baseurl: '/'      # the subpath of your site, e.g. /blog/
host: 'www.JKEEL.io' # the base hostname & protocol for your site
port: 80 
phoxygen_image: /img/JKEEL-logo.png

# User setting
owner: JKEEL
email: contact@JKEEL.io
twitter_username:  JKEELfins 
github_username:  JKEELfins 
facebook_username: JKEELfins
linkedin_username: JKEEL
address:
  - line: 15 Boulevard Marius Thomas
  - line: F-13007 Marseille
telephone: +33633184844
copyright: JKEEL

# API settings
google_api_key: AIzaSyBQR3mbhcM2LmwuHJWGLT7bGI36exTrOd0

# Build settings
markdown: kramdown

